version: '3'
services:
  music-db:
    container_name: music-db
    image: postgres:13.0
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: db
    ports:
      - 5432:5432